### ISSUE TITLE
Spring Config Client running into CodecException when used with Docker Native Image

### ISSUE THREAD

**Issue by realbucksavage** [micronaut-projects/micronaut-discovery-client#334]
### Expected Behavior

The spring cloud config client should be able to read and deserialize the JSON response from config server into a `ConfigServerResponse` instance. When this happens, a log entry similar to the one below can be seen:
```
Resolved XX configuration sources from client: compositeConfigurationClient(spring-cloud-config-client)
```

### Actual Behaviour

When running the `docker-native` image, a `io.micronaut.http.codec.CodecException` is thrown with cause `Cannot construct instance of `io.micronaut.discovery.spring.config.client.ConfigServerResponse` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)`.

<details>
    <summary>Stack trace</summary>

```
  Error starting Micronaut server: Error reading distributed configuration from Spring Cloud: Error decoding HTTP response body: Error decoding stream for type [class io.micronaut.discovery.spring.config.client.ConfigServerResponse]: Cannot construct instance of `io.micronaut.discovery.spring.config.client.ConfigServerResponse` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
   at [Source: (byte[])"{"name":"some-service","profiles":["cloud,staging"],"label":null,"version":"649fa009bd06a9c69c2b5809f2a4bb0559017d6c","state":null,"propertySources":[{"name":"https://git.myorg.com/configuration.git/some-service-staging.yml","source":{"mongodb.uri":"mongodb://template:template@localhost:27017/template110","mongodb.database":"template110"}},{"name":"https://git.myorg.com/configuration.git/application-stag"[truncated 691 bytes]; line: 1, column: 2]
  io.micronaut.context.exceptions.ConfigurationException: Error reading distributed configuration from Spring Cloud: Error decoding HTTP response body: Error decoding stream for type [class io.micronaut.discovery.spring.config.client.ConfigServerResponse]: Cannot construct instance of `io.micronaut.discovery.spring.config.client.ConfigServerResponse` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
   at [Source: (byte[])"{"name":"some-service","profiles":["cloud,staging"],"label":null,"version":"649fa009bd06a9c69c2b5809f2a4bb0559017d6c","state":null,"propertySources":[{"name":"https://git.myorg.com/configuration.git/some-service-staging.yml","source":{"mongodb.uri":"mongodb://template:template@localhost:27017/template110","mongodb.database":"template110"}},{"name":"https://git.myorg.com/configuration.git/application-stag"[truncated 691 bytes]; line: 1, column: 2]
          at io.micronaut.discovery.spring.config.SpringCloudConfigurationClient.lambda$getPropertySources$0(SpringCloudConfigurationClient.java:122)
          at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
          at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:132)
          at reactor.core.publisher.FluxSwitchMap$SwitchMapMain.checkTerminated(FluxSwitchMap.java:391)
          at reactor.core.publisher.FluxSwitchMap$SwitchMapMain.drain(FluxSwitchMap.java:338)
          at reactor.core.publisher.FluxSwitchMap$SwitchMapMain.innerError(FluxSwitchMap.java:424)
          at reactor.core.publisher.FluxSwitchMap$SwitchMapInner.onError(FluxSwitchMap.java:517)
          at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
          at reactor.core.publisher.Operators.error(Operators.java:198)
          at reactor.core.publisher.FluxError.subscribe(FluxError.java:43)
          at reactor.core.publisher.Flux.subscribe(Flux.java:8469)
          at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
          at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
          at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onError(FluxTimeout.java:219)
          at reactor.core.publisher.FluxCreate$BaseSink.error(FluxCreate.java:453)
          at reactor.core.publisher.FluxCreate$SerializedFluxSink.drainLoop(FluxCreate.java:230)
          at reactor.core.publisher.FluxCreate$SerializedFluxSink.drain(FluxCreate.java:206)
          at reactor.core.publisher.FluxCreate$SerializedFluxSink.error(FluxCreate.java:182)
          at io.micronaut.http.client.netty.DefaultHttpClient$11.channelReadInstrumented(DefaultHttpClient.java:2503)
          at io.micronaut.http.client.netty.DefaultHttpClient$11.channelReadInstrumented(DefaultHttpClient.java:2334)
          at io.micronaut.http.client.netty.DefaultHttpClient$SimpleChannelInboundHandlerInstrumented.channelRead0(DefaultHttpClient.java:3089)
          at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
          at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
          at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
          at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
          at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:214)
          at io.micronaut.http.netty.stream.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:189)
          at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
          at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
          at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
          at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
          at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
          at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
          at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
          at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
          at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
          at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
          at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
          at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
          at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
          at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
          at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
          at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
          at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
          at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
          at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
          at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
          at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
          at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
          at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
          at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
          at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
          at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
          at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
          at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
          at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
          at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
          at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
          at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
          at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
          at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
          at java.lang.Thread.run(Thread.java:829)
          at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
          at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
          Suppressed: java.lang.Exception: #block terminated with an error
                  at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
                  at reactor.core.publisher.Mono.block(Mono.java:1707)
                  at io.micronaut.discovery.client.config.DistributedPropertySourceLocator.findPropertySources(DistributedPropertySourceLocator.java:79)
                  at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.readPropertySourceList(DefaultApplicationContext.java:734)
                  at io.micronaut.context.env.DefaultEnvironment.readPropertySources(DefaultEnvironment.java:408)
                  at io.micronaut.context.env.DefaultEnvironment.start(DefaultEnvironment.java:270)
                  at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:720)
                  at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:689)
                  at io.micronaut.context.DefaultApplicationContext.startEnvironment(DefaultApplicationContext.java:230)
                  at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:182)
                  at io.micronaut.runtime.Micronaut.start(Micronaut.java:72)
                  at io.micronaut.runtime.Micronaut.run(Micronaut.java:313)
                  at io.micronaut.runtime.Micronaut.run(Micronaut.java:299)
                  at org.myorg.myapp.staging.Application.main(Application.java:10)
  Caused by: io.micronaut.http.client.exceptions.HttpClientResponseException: Error decoding HTTP response body: Error decoding stream for type [class io.micronaut.discovery.spring.config.client.ConfigServerResponse]: Cannot construct instance of `io.micronaut.discovery.spring.config.client.ConfigServerResponse` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
   at [Source: (byte[])"{"name":"some-service","profiles":["cloud,staging"],"label":null,"version":"649fa009bd06a9c69c2b5809f2a4bb0559017d6c","state":null,"propertySources":[{"name":"https://git.myorg.com/configuration.git/some-service-staging.yml","source":{"mongodb.uri":"mongodb://template:template@localhost:27017/template110","mongodb.database":"template110"}},{"name":"https://git.myorg.com/configuration.git/application-stag"[truncated 691 bytes]; line: 1, column: 2]
          at io.micronaut.http.client.netty.DefaultHttpClient$11.channelReadInstrumented(DefaultHttpClient.java:2491)
          ... 45 common frames omitted
  Caused by: io.micronaut.http.codec.CodecException: Error decoding stream for type [class io.micronaut.discovery.spring.config.client.ConfigServerResponse]: Cannot construct instance of `io.micronaut.discovery.spring.config.client.ConfigServerResponse` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
   at [Source: (byte[])"{"name":"some-service","profiles":["cloud,staging"],"label":null,"version":"649fa009bd06a9c69c2b5809f2a4bb0559017d6c","state":null,"propertySources":[{"name":"https://git.myorg.com/configuration.git/some-service-staging.yml","source":{"mongodb.uri":"mongodb://template:template@localhost:27017/template110","mongodb.database":"template110"}},{"name":"https://git.myorg.com/configuration.git/application-stag"[truncated 691 bytes]; line: 1, column: 2]
          at io.micronaut.json.codec.MapperMediaTypeCodec.decode(MapperMediaTypeCodec.java:192)
          at io.micronaut.http.client.netty.FullNettyClientHttpResponse.convertByteBuf(FullNettyClientHttpResponse.java:279)
          at io.micronaut.http.client.netty.FullNettyClientHttpResponse.lambda$getBody$1(FullNettyClientHttpResponse.java:217)
          at java.util.HashMap.computeIfAbsent(HashMap.java:1134)
          at io.micronaut.http.client.netty.FullNettyClientHttpResponse.getBody(FullNettyClientHttpResponse.java:191)
          at io.micronaut.http.client.netty.FullNettyClientHttpResponse.<init>(FullNettyClientHttpResponse.java:110)
          at io.micronaut.http.client.netty.DefaultHttpClient$11.channelReadInstrumented(DefaultHttpClient.java:2411)
          ... 45 common frames omitted
  Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `io.micronaut.discovery.spring.config.client.ConfigServerResponse` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
   at [Source: (byte[])"{"name":"some-service","profiles":["cloud,staging"],"label":null,"version":"649fa009bd06a9c69c2b5809f2a4bb0559017d6c","state":null,"propertySources":[{"name":"https://git.myorg.com/configuration.git/some-service-staging.yml","source":{"mongodb.uri":"mongodb://template:template@localhost:27017/template110","mongodb.database":"template110"}},{"name":"https://git.myorg.com/configuration.git/application-stag"[truncated 691 bytes]; line: 1, column: 2]
          at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1764)
          at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
          at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1209)
          at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1415)
          at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
          at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
          at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
          at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
          at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3643)
          at io.micronaut.jackson.databind.JacksonDatabindMapper.readValue(JacksonDatabindMapper.java:119)
          at io.micronaut.json.codec.MapperMediaTypeCodec.decode(MapperMediaTypeCodec.java:189)
          ... 51 common frames omitted
```

</details>

### Steps To Reproduce

- Create application from scratch
- Enable spring config client
- Build docker native image - `./gradlew clean dockerBuildNative`
- A container created out of this image should print out the error

### Environment Information

- **Operating System**: Pop!_OS 20.05 LTS
- **Micronaut Version**: 3.3.0
- **JDK Version**: OpenJDK 11

### Example Application

[realbucksavage/mn-native-config-demo](https://github.com/realbucksavage/mn-native-config-demo)

### Version

3.4.1

**Comment by realbucksavage** [comment]
The problem seems to go away when `@ReflectiveAccess` is added to `ConfigServerResponse` and `ConfigServerPropertySource` (see https://github.com/clowre/micronaut-discovery-client/commit/c323a49e4c28c9ea26c918a40ee6d306f9f9afe4).

I'll be glad to work on a patch of this issue that aligns with the project's goals.
