### ISSUE TITLE
Unable to run test locally

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-discovery-client#519]
```
% ./gradlew test --parallel         

Version catalog 'mnTest' can be automatically imported. You can remove it from settings.gradle(.kts) file.
Type-safe project accessors is an incubating feature.
Project accessors enabled, but root project name not explicitly set for 'buildSrc'. Checking out the project in different folders will impact the generated code and implicitly the buildscript classpath, breaking caching.

> Task :test-suite-consul-graal:internalStartTestResourcesService
[1.312s][warning][cds] Preload Warning: Cannot find io/netty/channel/$Proxy12
[1.767s][warning][cds] Skipping jdk/internal/event/Event: JFR event class
[1.769s][warning][cds] Skipping jdk/internal/event/ProcessStartEvent: JFR event class
[1.769s][warning][cds] Skipping jdk/internal/event/SecurityProviderServiceEvent: JFR event class

[test-resources-service] 12:00:33.272 [ForkJoinPool.commonPool-worker-20] INFO  i.m.t.e.TestResourcesResolverLoader - Loaded 1 test resources resolvers: io.micronaut.testresources.testcontainers.GenericTestContainerProvider

> Task :micronaut-discovery-client:testecuting test io.micronaut.discovery.consul.ConsulMockAutoRegistrationSpec


Predictive Test Selection: all test classes selected
Test Run :micronaut-discovery-client:test > Partition 1 in session 1 on localhost-executor-1 > ConsulMockAutoRegistrationSpec test mock server PASSED

  SLF4J: No SLF4J providers were found.
  SLF4J: Defaulting to no-operation (NOP) logger implementation
  SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.

Test Run :micronaut-discovery-client:test > Partition 1 in session 1 on localhost-executor-1 > ConsulMockAutoRegistrationSpec test that the service is automatically registered with Consul PASSED
Test Run :micronaut-discovery-client:test > Partition 1 in session 1 on localhost-executor-1 > ConsulMockAutoRegistrationSpec test that the service is automatically de-registered with Consul PASSED
Test Run :micronaut-discovery-client:test > Partition 1 in session 1 on localhost-executor-1 > ConsulMockAutoRegistrationSpec test that a service can be registered with tags PASSED

[test-resources-service] 12:00:33.373 [main] INFO  i.m.t.server.TestResourcesService - A Micronaut Test Resources server is listening on port 65349, started in 153ms
[test-resources-service] 12:00:34.600 [default-nioEventLoopGroup-1-2] INFO  i.m.t.e.TestResourcesResolverLoader - Loaded 1 test resources resolvers: io.micronaut.testresources.testcontainers.GenericTestContainerProvider
[test-resources-service] 12:00:34.843 [default-nioEventLoopGroup-1-2] INFO  o.t.utility.ImageNameSubstitutor - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')eted
[test-resources-service] 12:00:34.845 [default-nioEventLoopGroup-1-2] INFO  i.m.t.testcontainers.TestContainers - Starting test container consul
[test-resources-service] 12:00:34.958 [default-nioEventLoopGroup-1-2] INFO  o.t.d.DockerClientProviderStrategy - Found Docker environment with Testcontainers Host with tc.host=tcp://127.0.0.1:65500
[test-resources-service] 12:00:34.959 [default-nioEventLoopGroup-1-2] INFO  o.testcontainers.DockerClientFactory - Docker host IP address is 127.0.0.1
[test-resources-service] 12:00:34.962 [default-nioEventLoopGroup-1-2] INFO  o.testcontainers.DockerClientFactory - Connected to docker: 
  Server Version: 24.0.6 (via Testcontainers Desktop 1.4.16)
  API Version: 1.43l-graal:test > Executing test io.micronaut.consul.graal.ConsulTest
  Operating System: Docker Desktop
  Total Memory: 48105 MB
[test-resources-service] 12:00:34.964 [default-nioEventLoopGroup-1-2] INFO  o.testcontainers.DockerClientFactory - Checking the system...
[test-resources-service] 12:00:34.964 [default-nioEventLoopGroup-1-2] INFO  o.testcontainers.DockerClientFactory - ✔︎ Docker server version should be at least 1.6.0
[test-resources-service] 12:00:34.979 [default-nioEventLoopGroup-1-2] INFO  tc.consul:1.9.0 - Creating container for image: consul:1.9.0
[test-resources-service] 12:00:35.112 [default-nioEventLoopGroup-1-2] INFO  tc.testcontainers/ryuk:0.5.1 - Creating container for image: testcontainers/ryuk:0.5.1
[test-resources-service] 12:00:40.040 [default-nioEventLoopGroup-1-2] INFO  tc.testcontainers/ryuk:0.5.1 - Container testcontainers/ryuk:0.5.1 is starting: ccc3906f6ec98de7e8355b9d87f71e1b7547356ed3651e3258ca95d7254776b9
[test-resources-service] 12:00:41.246 [default-nioEventLoopGroup-1-2] INFO  tc.testcontainers/ryuk:0.5.1 - Container testcontainers/ryuk:0.5.1 started in PT6.134272S
[test-resources-service] 12:00:41.270 [default-nioEventLoopGroup-1-2] INFO  tc.consul:1.9.0 - Container consul:1.9.0 is starting: e9ed335d684538878ee6ee8a7a22e743c4bc42f1492794a558aa85c2556cabd1
[test-resources-service] 12:00:41.397 [default-nioEventLoopGroup-1-2] INFO  o.t.c.wait.strategy.HttpWaitStrategy - /inspiring_lalande: Waiting for 60 seconds for URL: http://127.0.0.1:65393/v1/status/leader (where port 65393 maps to container port 8500)l:test > 0 tests completed
[test-resources-service] 12:00:42.411 [default-nioEventLoopGroup-1-2] INFO  tc.consul:1.9.0 - Container consul:1.9.0 started in PT7.446201S

> Task :micronaut-discovery-client:test
Test Run :micronaut-discovery-client:test > Partition 1 in session 1 on localhost-executor-1 > ConsulMockAutoRegistrationSpec test that a service can be registered with metadata PASSED (30s)
Test Run :micronaut-discovery-client:test > Partition 1 in session 1 on localhost-executor-1 > ConsulMockAutoRegistrationSpec test that a service can be registered with an HTTP health check PASSED
Test Run :micronaut-discovery-client:test > Partition 1 in session 1 on localhost-executor-1 > ConsulMockAutoRegistrationSpec test that a service can be registered with an HTTP health check and deregisterCriticalServiceAfter PASSEDDLE
Test Run :micronaut-discovery-client:test > Partition 1 in session 1 on localhost-executor-1 > ConsulMockAutoRegistrationSpec test that a service can be registered with an HTTP health check and tlsSkipVerify PASSED
Test Run :micronaut-discovery-client:test > Partition 1 in session 1 on localhost-executor-1 > ConsulMockAutoRegistrationSpec test that a service can be registered with an HTTP health check and HTTP method PASSED
Test Run :micronaut-discovery-client:test > Partition 1 in session 1 on localhost-executor-1 > ConsulMockAutoRegistrationSpec test that a asl token can be configured PASSED
Test Run :micronaut-discovery-client:test > Partition 2 in session 1 on localhost-executor-1 > EurekaAutoRegistrationSpec test that an application can be registered and de-registered with Eureka PASSED (17.1s)
Test Run :micronaut-discovery-client:test > Partition 3 in session 1 on localhost-executor-1 > EurekaClientSpec test is a discovery client PASSED
Test Run :micronaut-discovery-client:test > Partition 3 in session 1 on localhost-executor-1 > EurekaClientSpec test validation PASSED
Test Run :micronaut-discovery-client:test > Partition 3 in session 1 on localhost-executor-1 > EurekaClientSpec test register and de-register instance PASSED
Test Run :micronaut-discovery-client:test > Partition 6 in session 1 on localhost-executor-1 > VaultJacksonIntegrationTest test list secrets from vault PASSED (1.3s)
Test Run :micronaut-discovery-client:test > Partition 6 in session 1 on localhost-executor-1 > ClientScopeSpec test that a client can be discovered using @Client scope PASSED (3.1s)
Test Run :micronaut-discovery-client:test > Partition 6 in session 1 on localhost-executor-1 > ClientScopeSpec test that a client can be discovered using @Client scope with Consul  SKIPPED
Test Run :micronaut-discovery-client:test > Partition 7 in session 1 on localhost-executor-1 > ConsulAutoRegistrationSpec test that the service is automatically registered with Consul with a TTL configuration PASSED
Test Run :micronaut-discovery-client:test > Partition 7 in session 1 on localhost-executor-1 > ConsulAutoRegistrationSpec test that the service is automatically registered with Consul with a HTTP configuration PASSED
Test Run :micronaut-discovery-client:test > Partition 7 in session 1 on localhost-executor-1 > ConsulAutoRegistrationSpec test that a service can be registered with tags and queried with tags PASSED
Test Run :micronaut-discovery-client:test > Partition 7 in session 1 on localhost-executor-1 > ConsulAutoRegistrationSpec test that a service can be registered with metadata PASSED
Test Run :micronaut-discovery-client:test > Partition 7 in session 1 on localhost-executor-1 > ConsulAutoRegistrationSpec test that when Consul is explicitly configured, no AWS service discovery stuff is registered PASSED
Test Run :micronaut-discovery-client:test > Partition 7 in session 1 on localhost-executor-1 > ConsulAutoRegistrationSpec test auto-registration with checks PASSED
Test Run :micronaut-discovery-client:test > Partition 7 in session 1 on localhost-executor-1 > EurekaMockAutoRegistrationSpec test that an application can be registered and de-registered with Eureka hyphenated PASSED
Test Run :micronaut-discovery-client:test > Partition 7 in session 1 on localhost-executor-1 > EurekaMockAutoRegistrationSpec test that an application can be registered and de-registered with Eureka PASSED
Test Run :micronaut-discovery-client:test > Partition 7 in session 1 on localhost-executor-1 > EurekaMockAutoRegistrationSpec > test that an application can be registered and de-registered with Eureka with metadata test that an application can be registered and de-registered with Eureka with metadata [serviceId: myService, configuration: [asgName:test, vipAddress:myVip, secureVipAddress:mySecureVip, appGroupName:myAppGroup, status:STARTING], #0] PASSE
Test Run :micronaut-discovery-client:test > Partition 7 in session 1 on localhost-executor-1 > EurekaMockAutoRegistrationSpec > test that an application can be registered and de-registered with Eureka with metadata test that an application can be registered and de-registered with Eureka with metadata [serviceId: myService, configuration: [homePageUrl:http://home, statusPageUrl:http://status, healthCheckUrl:http://health, secureHealthCheckUrl:http://securehealth], #1] PASSED
Test Run :micronaut-discovery-client:test > Partition 7 in session 1 on localhost-executor-1 > EurekaMockAutoRegistrationSpec > test that an application can be registered and de-registered with Eureka with metadata test that an application can be registered and de-registered with Eureka with metadata [serviceId: myService, configuration: [metadata:[foo:bar]], #2] PASSED
Test Run :micronaut-discovery-client:test > Partition 7 in session 1 on localhost-executor-1 > EurekaMockAutoRegistrationSpec > test that an application can be registered and de-registered with Eureka with metadata test that an application can be registered and de-registered with Eureka with metadata [serviceId: myService, configuration: [port:9999, securePort:9998], #3] PASSED
Test Run :micronaut-discovery-client:test > Partition 8 in session 1 on localhost-executor-1 > ConsulClientSpec test is a discovery client PASSED
Test Run :micronaut-discovery-client:test > Partition 8 in session 1 on localhost-executor-1 > ConsulClientSpec test list services PASSED
Test Run :micronaut-discovery-client:test > Partition 8 in session 1 on localhost-executor-1 > ConsulClientSpec test register and deregister catalog entry PASSED
Test Run :micronaut-discovery-client:test > Partition 8 in session 1 on localhost-executor-1 > ConsulClientSpec test register and deregister service entry PASSED
Test Run :micronaut-discovery-client:test > Partition 8 in session 1 on localhost-executor-1 > ConsulClientSpec test register service with health check PASSED
Test Run :micronaut-discovery-client:test > Partition 8 in session 1 on localhost-executor-1 > ConsulClientSpec test list members PASSED
Test Run :micronaut-discovery-client:test > Partition 8 in session 1 on localhost-executor-1 > ConsulClientSpec test get self PASSED
Test Run :micronaut-discovery-client:test > Partition 8 in session 1 on localhost-executor-1 > EagerInitSpec test run with eager init PASSED
Test Run :micronaut-discovery-client:test > Partition 8 in session 1 on localhost-executor-1 > ConsulHealthStatusSpec test the consul service's health status is correct PASSED
Test Run :micronaut-discovery-client:test > Partition 8 in session 1 on localhost-executor-1 > EurekaMockHeartbeatSpec test that the server reports a heartbeat to Eureka PASSED (5s)
Test Run :micronaut-discovery-client:test > Partition 8 in session 1 on localhost-executor-1 > EurekaClientConfigSpec > test configure default zone test configure default zone [value: localhost:8087, result: [http://localhost:8087 (eureka)], #0] PASSED
Test Run :micronaut-discovery-client:test > Partition 8 in session 1 on localhost-executor-1 > EurekaClientConfigSpec > test configure default zone test configure default zone [value: localhost:8087,localhost:8088, result: [http://localhost:8087 (eureka), http://localhost:8088 (eureka)], #1] PASSED
Test Run :micronaut-discovery-client:test > Partition 8 in session 1 on localhost-executor-1 > EurekaClientConfigSpec > test configure other zones test configure other zones [value: localhost:8087, result: [http://localhost:8087 (eureka)], #0] PASSED
Test Run :micronaut-discovery-client:test > Partition 8 in session 1 on localhost-executor-1 > EurekaClientConfigSpec > test configure other zones test configure other zones [value: localhost:8087,localhost:8088, result: [http://localhost:8087 (eureka), http://localhost:8088 (eureka)], #1] PASSED
Test Run :micronaut-discovery-client:test > Partition 8 in session 1 on localhost-executor-1 > EurekaClientConfigSpec test configure registration client PASSED
Test Run :micronaut-discovery-client:test > Partition 8 in session 1 on localhost-executor-1 > EurekaClientConfigSpec > should correctly setup instance info (prefer ip-addr: #preferIpAddr) should correctly setup instance info (prefer ip-addr: true) PASSED
Test Run :micronaut-discovery-client:test > Partition 8 in session 1 on localhost-executor-1 > EurekaClientConfigSpec > should correctly setup instance info (prefer ip-addr: #preferIpAddr) should correctly setup instance info (prefer ip-addr: false) PASSED
Test Run :micronaut-discovery-client:test > Partition 8 in session 1 on localhost-executor-1 > EurekaClientConfigSpec > should correctly setup instance info with overrides from configuration properties (prefer ip-addr: #preferIpAddr) should correctly setup instance info with overrides from configuration properties (prefer ip-addr: true) PASSED
Test Run :micronaut-discovery-client:test > Partition 8 in session 1 on localhost-executor-1 > EurekaClientConfigSpec > should correctly setup instance info with overrides from configuration properties (prefer ip-addr: #preferIpAddr) should correctly setup instance info with overrides from configuration properties (prefer ip-addr: false) PASSED
Test Run :micronaut-discovery-client:test > Partition 4 in session 1 on localhost-executor-1 > TtlHeartbeatSpec test that the server reports a TTL heartbeat when configured to do so PASSED (5.1s)
Test Run :micronaut-discovery-client:test > Partition 4 in session 1 on localhost-executor-1 > TtlHeartbeatSpec test that if the consul server goes down and comes back up the application re-registers SKIPPED
Test Run :micronaut-discovery-client:test > Partition 5 in session 1 on localhost-executor-1 > EurekaContextPathSpec test that the server reports a heartbeat to Eureka PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > MockConfigurationDiscoverySpec test read application configuration from Consul PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > MockConfigurationDiscoverySpec test multiple environment precedence PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > MockConfigurationDiscoverySpec test disable application configuration from Consul PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > ConsulMockConfigurationClientFilesSpec test discovery property sources from Consul with YAML handling PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > EurekaMockBasicAuthSpec test authentication works PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > SpringCloudConfigSecuredTest test spring name configuration field when server secured and authorization provided PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > SpringCloudConfigSecuredTest test when cloud server secured and authorization not provided PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > SpringCloudConfigSecuredTest test when cloud server secured and only username is provided PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > SpringCloudConfigSecuredTest test when cloud server secured and invalid user credentials provided PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > CompositeDiscoverySpec test multiple service discovery clients PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > ConsulMockHealthStatusSpec test the consul service's health status is correct PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > VaultClientV2ConfigTest test configuration order PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > VaultClientV2ConfigTest test prefixed configuration order PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > DigitalOceanMetadataResolverSpec test building digital ocean compute metadata PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > EurekaEnabledSpec test client is not enabled with no config PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > EurekaEnabledSpec test client is enabled with service discovery settings PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > EurekaEnabledSpec test client is enabled with service discovery enabled PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > EurekaEnabledSpec test client is enabled with registration settings PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > EurekaEnabledSpec test client is enabled with registration enabled PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > EurekaEnabledSpec test client is disabled if both registration and discovery are disabled PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > VaultClientV1ConfigTest test configuration order PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > VaultClientV1ConfigTest test prefixed configuration order PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > EurekaHealthIndicatorSpec test eureka health indicator PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > SpringCloudConfigTest test configuration order PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > SpringCloudConfigTest test spring name configuration field PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > ConsulMockConfigurationClientYamlSpec initializationError FAILED

  java.lang.IllegalStateException: failed to create a child event loop
      at app//io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
      at app//io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:60)
      at app//io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:49)
      at app//io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
      at app//io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:87)
      at app//io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:82)
      at app//io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:69)
      at app//io.micronaut.http.netty.channel.NioEventLoopGroupFactory.createEventLoopGroup(NioEventLoopGroupFactory.java:56)
      at app//io.micronaut.http.netty.channel.EventLoopGroupFactory.createEventLoopGroup(EventLoopGroupFactory.java:75)
      at app//io.micronaut.http.netty.channel.DefaultEventLoopGroupFactory.createEventLoopGroup(DefaultEventLoopGroupFactory.java:96)
      at app//io.micronaut.http.server.netty.DefaultNettyEmbeddedServerFactory.createEventLoopGroup(DefaultNettyEmbeddedServerFactory.java:284)
      at app//io.micronaut.http.server.netty.NettyHttpServer.newEventLoopGroup(NettyHttpServer.java:688)
      at app//io.micronaut.http.server.netty.NettyHttpServer.lambda$createParentEventLoopGroup$11(NettyHttpServer.java:478)
      at java.base@17.0.8/java.util.Optional.orElseGet(Optional.java:364)
      at app//io.micronaut.http.server.netty.NettyHttpServer.createParentEventLoopGroup(NettyHttpServer.java:477)
      at app//io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:272)
      at app//io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:104)
      at app//io.micronaut.context.ApplicationContext.run(ApplicationContext.java:238)
      at app//io.micronaut.context.ApplicationContext.run(ApplicationContext.java:210)
      at app//io.micronaut.discovery.consul.ConsulMockConfigurationClientYamlSpec.$spock_initializeSharedFields(ConsulMockConfigurationClientYamlSpec.groovy:36)
  Caused by: io.netty.channel.ChannelException: failed to open a new selector
      at app//io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:179)
      at app//io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:146)
      at app//io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:183)
      at app//io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:38)
      at app//io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
      ... 19 more
  Caused by: java.io.IOException: Too many open files
      at java.base@17.0.8/sun.nio.ch.KQueueSelectorImpl.<init>(KQueueSelectorImpl.java:82)
      at java.base@17.0.8/sun.nio.ch.KQueueSelectorProvider.openSelector(KQueueSelectorProvider.java:36)
      at app//io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:177)
      ... 23 more

Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > ConsulMockConfigurationClientJsonSpec test discovery property sources from Consul with JSON handling PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > ConsulMockConfigurationClientJsonSpec test discovery property sources from Consul with invalid JSON PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > ConsulMockConfigurationClientNativeSpec test read and write key values with ConsulClient PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > ConsulMockConfigurationClientNativeSpec test discovery property sources from Consul with native property handling PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > EurekaInstanceInfoSpec test deserialize amazon instance info PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > DiscoveryClientHealthIndicatorConfigurationSpec test that the health indicator configuration is not available when disabled via config PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > DiscoveryClientHealthIndicatorConfigurationSpec test that the health indicator configuration is available when no entry is in config PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > ConsulMockConfigurationClientPropertiesSpec test discovery property sources from Consul with Properties file handling PASSED
Test Run :micronaut-discovery-client:test > Partition 9 in session 1 on localhost-executor-1 > InstanceInfoSpec test instance info PASSED

FAILURE: Executed 86 tests in 1m 33s (1 failed, 2 skipped)



86 tests completed, 1 failed, 2 skipped

> Task :micronaut-discovery-client:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':micronaut-discovery-client:test'.
> There were failing tests. See the report at: file:///Users/sdelamo/github/micronaut-projects/micronaut-discovery-client/discovery-client/build/reports/tests/test/index.html

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 1m 34s
22 actionable tasks: 4 executed, 2 from cache, 16 up-to-date

Publishing build scan...
https://ge.micronaut.io/s/xkc4dflt7k5dk

```

**Comment by sdelamo** [comment]
I think it is better to split the tests in multiple project but I am no longer able to reproduce this issue.
